name = "eyesentry"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "dist"

[site]
bucket = "./dist"
include = ["**/*"]
exclude = ["node_modules/*"]

[build]
command = "npm run build"
cwd = "."

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 